const objets = [
  
  // FEU
  {
    nom: "Talisman du feu",
    description: "Augmente les dégâts de feu de 5, donne 10 mana et rapporte 42 XP.",
    hp: 0,
    bonus: 5,
    mana: 10,
    category: "feu",
    xp: 42,
  },
  {
    nom: "Cape flamboyante",
    description: "Augmente les dégâts de feu de 3, donne 15 PV et rapporte 60 XP.",
    hp: 15,
    bonus: 3,
    category: "feu",
    xp: 60,
  },
  {
    nom: "Bague incandescente",
    description: "Augmente les dégâts de feu de 2, donne 5 mana et rapporte 18 XP.",
    hp: 0,
    bonus: 2,
    mana: 5,
    category: "feu",
    xp: 18,
  },
  {
    nom: "Sceptre volcanique",
    description: "Augmente les dégâts de feu de 4, donne 20 PV et rapporte 75 XP.",
    hp: 20,
    bonus: 4,
    category: "feu",
    xp: 75,
  },
  {
    nom: "Amulette ardente",
    description: "Augmente les dégâts de feu de 3, donne 10 PV, 5 mana et rapporte 33 XP.",
    hp: 10,
    bonus: 3,
    mana: 5,
    category: "feu",
    xp: 33,
  },

  // ... Répète ce modèle pour chaque objet, en adaptant la description :
  // - Ajoute "et rapporte XX XP." à la fin
  // - Si l'objet donne plusieurs bonus, sépare-les par des virgules
  // - Si l'objet donne PV, mana, etc., précise-les dans la description

  // Exemple pour un objet "tout"
  {
    nom: "Pierre universelle",
    description: "Augmente les dégâts de toutes les compétences de 2, donne 10 mana et rapporte 30 XP.",
    hp: 0,
    bonus: 2,
    mana: 10,
    category: "tout",
    xp: 30,
  },
  {
    nom: "Gants de la victoire",
    description: "Augmente les dégâts de toutes les compétences de 1, donne 10 PV, 5 mana et rapporte 18 XP.",
    hp: 10,
    bonus: 1,
    mana: 5,
    category: "tout",
    xp: 18,
  },
  {
    nom: "Couronne du Roi-Dieu",
    description: "Légendaire : +5 dégâts, +50 PV, +50 mana, +100 XP.",
    bonus: 5,
    hp: 50,
    mana: 50,
    xp: 100,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Étoile du Destin",
    description: "Légendaire : +4 dégâts, +40 PV, +40 mana, +80 XP.",
    bonus: 4,
    hp: 40,
    mana: 40,
    xp: 80,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Anneau de l'Éternité",
    description: "Légendaire : +3 dégâts, +30 PV, +60 mana, +60 XP.",
    bonus: 3,
    hp: 30,
    mana: 60,
    xp: 60,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Cape du Phénix",
    description: "Légendaire : +6 dégâts, +60 PV, +30 mana, +120 XP.",
    bonus: 6,
    hp: 60,
    mana: 30,
    xp: 120,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Sceptre des Anciens",
    description: "Légendaire : +7 dégâts, +35 PV, +70 mana, +140 XP.",
    bonus: 7,
    hp: 35,
    mana: 70,
    xp: 140,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Médaillon du Crépuscule",
    description: "Légendaire : +4 dégâts, +80 PV, +20 mana, +90 XP.",
    bonus: 4,
    hp: 80,
    mana: 20,
    xp: 90,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Talisman du Dragon",
    description: "Légendaire : +8 dégâts, +20 PV, +80 mana, +160 XP.",
    bonus: 8,
    hp: 20,
    mana: 80,
    xp: 160,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Orbe de l'Infini",
    description: "Légendaire : +5 dégâts, +100 PV, +50 mana, +200 XP.",
    bonus: 5,
    hp: 100,
    mana: 50,
    xp: 200,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Gants de la Légende",
    description: "Légendaire : +6 dégâts, +60 PV, +60 mana, +60 XP.",
    bonus: 6,
    hp: 60,
    mana: 60,
    xp: 60,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Ceinture du Titan",
    description: "Légendaire : +7 dégâts, +70 PV, +30 mana, +110 XP.",
    bonus: 7,
    hp: 70,
    mana: 30,
    xp: 110,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Amulette de l'Immortel",
    description: "Légendaire : +9 dégâts, +90 PV, +90 mana, +180 XP.",
    bonus: 9,
    hp: 90,
    mana: 90,
    xp: 180,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Bouclier du Gardien",
    description: "Légendaire : +4 dégâts, +120 PV, +20 mana, +100 XP.",
    bonus: 4,
    hp: 120,
    mana: 20,
    xp: 100,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Bottes du Voyageur",
    description: "Légendaire : +3 dégâts, +30 PV, +100 mana, +70 XP.",
    bonus: 3,
    hp: 30,
    mana: 100,
    xp: 70,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Larme de l'Oracle",
    description: "Légendaire : +5 dégâts, +50 PV, +150 mana, +150 XP.",
    bonus: 5,
    hp: 50,
    mana: 150,
    xp: 150,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Plume de l'Aube",
    description: "Légendaire : +2 dégâts, +20 PV, +200 mana, +50 XP.",
    bonus: 2,
    hp: 20,
    mana: 200,
    xp: 50,
    category: "tout",
    legendaire: true,
  },
  {
    nom: "Cristal du Cosmos",
    description: "Légendaire : +10 dégâts, +100 PV, +100 mana, +250 XP.",
    bonus: 10,
    hp: 100,
    mana: 100,
    xp: 250,
    category: "tout",
    legendaire: true,
  },
];

export default objets;
